/**
 * This file was generated by the Jeddict
 */
package theschoolmanagmentsystem.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author ITHSivju
 */
@Entity
public class Student implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long pn;

    @Basic
    private String firstName;

    @Basic
    private String surName;

    @ManyToOne
    private Education education;

    public Long getPn() {
        return this.pn;
    }

    public void setPn(Long pn) {
        this.pn = pn;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSurName() {
        return this.surName;
    }

    public void setSurName(String surName) {
        this.surName = surName;
    }

    public Education getEducation() {
        return this.education;
    }

    public void setEducation(Education education) {
        this.education = education;
    }

    @Override
    public String toString() {
        return "- Student: " + firstName + " " + surName + ",\tPersonal identification number " + pn;
    }

    
}